//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        public action()
        {
            this.user_permission = new HashSet<user_permission>();
            this.user_permission1 = new HashSet<user_permission>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> caticory_id { get; set; }
        public string action_description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual action_caticory action_caticory { get; set; }
        public virtual ICollection<user_permission> user_permission { get; set; }
        public virtual ICollection<user_permission> user_permission1 { get; set; }
    }
}
