//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_caticory
    {
        public action_caticory()
        {
            this.action = new HashSet<action>();
        }
    
        public System.Guid ID { get; set; }
        public string caticory { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual ICollection<action> action { get; set; }
    }
}
