//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public asset()
        {
            this.asset_credit = new HashSet<asset_credit>();
            this.asset_debit = new HashSet<asset_debit>();
        }
    
        public int الرقم { get; set; }
        public string اسم_الأصل { get; set; }
        public double الرصيد { get; set; }
        public string الرصيد_كتابة { get; set; }
        public System.DateTime تاريخ { get; set; }
        public string نوع_الأصل { get; set; }
        public Nullable<int> نسبة_الأهتلاك { get; set; }
        public Nullable<int> قيمة_النفاية { get; set; }
        public Nullable<int> مجمع_الإهتلاك { get; set; }
        public string نوع_الاصل { get; set; }
        public Nullable<int> نسبة_الاهتلاك { get; set; }
    
        public virtual ICollection<asset_credit> asset_credit { get; set; }
        public virtual ICollection<asset_debit> asset_debit { get; set; }
    }
}
