//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_account
    {
        public bank_account()
        {
            this.bank_credit = new HashSet<bank_credit>();
            this.bank_debit = new HashSet<bank_debit>();
        }
    
        public System.Guid الرقم { get; set; }
        public string اسم_الحساب { get; set; }
        public string رقم_الحساب { get; set; }
        public string نوع_الحساب { get; set; }
        public double الرصيد { get; set; }
        public string الرصيد_كتابة { get; set; }
        public System.DateTime تاريخ { get; set; }
        public Nullable<System.Guid> bank_id { get; set; }
        public string تعليق { get; set; }
    
        public virtual bank_details bank_details { get; set; }
        public virtual ICollection<bank_credit> bank_credit { get; set; }
        public virtual ICollection<bank_debit> bank_debit { get; set; }
    }
}
