//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_details
    {
        public bank_details()
        {
            this.bank_account = new HashSet<bank_account>();
        }
    
        public System.Guid الرقم { get; set; }
        public string اسم_البنك { get; set; }
        public string عنوان_البنك { get; set; }
        public string هاتف { get; set; }
        public string الموبايل { get; set; }
        public string البريد_الالكتروني { get; set; }
        public string الموقع_الالكتروني { get; set; }
        public string تعليق { get; set; }
        public string code { get; set; }
        public Nullable<System.Guid> companyID { get; set; }
    
        public virtual ICollection<bank_account> bank_account { get; set; }
    }
}
