//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class box
    {
        public box()
        {
            this.box_credit = new HashSet<box_credit>();
            this.box_debit = new HashSet<box_debit>();
        }
    
        public int الرقم { get; set; }
        public string اسم_الصندوق { get; set; }
        public double الرصيد { get; set; }
        public string الرصيد_كتابة { get; set; }
        public System.DateTime تاريخ { get; set; }
    
        public virtual ICollection<box_credit> box_credit { get; set; }
        public virtual ICollection<box_debit> box_debit { get; set; }
    }
}
