//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public Currencies()
        {
            this.company = new HashSet<company>();
            this.ExchangeRates = new HashSet<ExchangeRates>();
        }
    
        public int CurrencyID { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public string Symbol { get; set; }
    
        public virtual ICollection<company> company { get; set; }
        public virtual ICollection<ExchangeRates> ExchangeRates { get; set; }
    }
}
