//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class error
    {
        public int الرقم { get; set; }
        public string @class { get; set; }
        public string error_ms { get; set; }
        public Nullable<int> error_row { get; set; }
    }
}
