//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRates
    {
        public System.Guid RateID { get; set; }
        public int CurrencyID { get; set; }
        public decimal ExchangeRate { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Currencies Currencies { get; set; }
    }
}
