//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_maker_list
    {
        public int رقم_المادة { get; set; }
        public int رقم_المصنع { get; set; }
        public string اسم_المادة { get; set; }
        public string الوحدة { get; set; }
        public int كمية { get; set; }
        public double سعر_الشراء { get; set; }
        public double نسبة_الهدر { get; set; }
        public double كلفة_المادة { get; set; }
        public string ملاحظات { get; set; }
    
        public virtual material material { get; set; }
        public virtual material_maker material_maker { get; set; }
    }
}
