//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialMaker_credit
    {
        public materialMaker_credit()
        {
            this.materialMaker_credit_list = new HashSet<materialMaker_credit_list>();
        }
    
        public int الرقم { get; set; }
        public System.DateTime تاريخ_بدائية_التصنيع { get; set; }
        public System.DateTime تاريخ_نهاية_التصنيع { get; set; }
        public double الكلفة { get; set; }
        public string الرصيد_كتابة { get; set; }
        public string الى { get; set; }
        public string المستودع { get; set; }
        public Nullable<double> هدر { get; set; }
        public Nullable<double> مصاريف_مضافة { get; set; }
        public Nullable<double> كمية_الانتاج { get; set; }
    
        public virtual ICollection<materialMaker_credit_list> materialMaker_credit_list { get; set; }
    }
}
