//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public material()
        {
            this.material_cost = new HashSet<material_cost>();
            this.material_credit_list = new HashSet<material_credit_list>();
            this.material_credit_list_return = new HashSet<material_credit_list_return>();
            this.material_debit_list = new HashSet<material_debit_list>();
            this.material_debit_list_return = new HashSet<material_debit_list_return>();
            this.materialMaker_credit_list = new HashSet<materialMaker_credit_list>();
        }
    
        public int الرقم_الفني { get; set; }
        public string اسم_المادة { get; set; }
        public string تواجد_المادة { get; set; }
        public string الوحدة { get; set; }
        public int كمية { get; set; }
        public double سعر { get; set; }
        public string رمز_الطراز { get; set; }
        public Nullable<int> المجموعة { get; set; }
        public Nullable<int> الصانع { get; set; }
        public string بالة { get; set; }
        public Nullable<int> المستودع { get; set; }
        public string وصف_المادة { get; set; }
        public string صورة { get; set; }
        public Nullable<int> فرق_السعر { get; set; }
        public Nullable<int> فرق_الكمية { get; set; }
        public Nullable<int> سعر_الشراء { get; set; }
        public Nullable<int> سعر_البيع { get; set; }
        public string كود_المادة { get; set; }
        public Nullable<int> فرق_القيمة { get; set; }
        public string طريقة_حساب_الكلفة { get; set; }
    
        public virtual ICollection<material_cost> material_cost { get; set; }
        public virtual ICollection<material_credit_list> material_credit_list { get; set; }
        public virtual ICollection<material_credit_list_return> material_credit_list_return { get; set; }
        public virtual ICollection<material_debit_list> material_debit_list { get; set; }
        public virtual ICollection<material_debit_list_return> material_debit_list_return { get; set; }
        public virtual producer producer { get; set; }
        public virtual material_group material_group { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual ICollection<materialMaker_credit_list> materialMaker_credit_list { get; set; }
    }
}
