//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_credit
    {
        public material_credit()
        {
            this.material_credit_list = new HashSet<material_credit_list>();
            this.material_credit_penfit_payment = new HashSet<material_credit_penfit_payment>();
        }
    
        public int الرقم { get; set; }
        public System.DateTime تاريخ_البيع { get; set; }
        public System.DateTime تاريخ_التسليم { get; set; }
        public double الرصيد { get; set; }
        public string الرصيد_كتابة { get; set; }
        public string إلى { get; set; }
        public string طريقة_الدفع { get; set; }
        public string المستودع { get; set; }
        public int العميل { get; set; }
        public string حذفة { get; set; }
        public string بالة { get; set; }
        public string نوع_العملية { get; set; }
        public Nullable<double> حسم_ممنوح { get; set; }
        public Nullable<double> مصاريف_مضافة { get; set; }
        public string مصاريف_على_حساب { get; set; }
        public string مرحل { get; set; }
        public string اسم_الحساب { get; set; }
        public Nullable<int> سند_القبض { get; set; }
        public Nullable<int> الفائدة { get; set; }
        public Nullable<int> الدفع_كل { get; set; }
        public Nullable<int> عدد_الأقساط { get; set; }
        public Nullable<double> الكلفة { get; set; }
        public string اسم_ممنوح { get; set; }
        public Nullable<int> عدد_الاقساط { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<material_credit_list> material_credit_list { get; set; }
        public virtual ICollection<material_credit_penfit_payment> material_credit_penfit_payment { get; set; }
    }
}
