//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_debit_penfit_payment
    {
        public System.Guid الرقم { get; set; }
        public System.Guid رقم_التقرير { get; set; }
        public int الفائدة { get; set; }
        public int نسبة_الفائدة { get; set; }
        public int الدفع_كل { get; set; }
        public int عدد_الأقساط { get; set; }
        public Nullable<int> العربون { get; set; }
    
        public virtual material_debit material_debit { get; set; }
    }
}
