//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingEntities : DbContext
    {
        public AccountingEntities()
            : base("name=AccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<action> action { get; set; }
        public DbSet<action_caticory> action_caticory { get; set; }
        public DbSet<asset> asset { get; set; }
        public DbSet<asset_credit> asset_credit { get; set; }
        public DbSet<asset_debit> asset_debit { get; set; }
        public DbSet<audit> audit { get; set; }
        public DbSet<bank_account> bank_account { get; set; }
        public DbSet<bank_credit> bank_credit { get; set; }
        public DbSet<bank_debit> bank_debit { get; set; }
        public DbSet<bank_details> bank_details { get; set; }
        public DbSet<bonds> bonds { get; set; }
        public DbSet<box> box { get; set; }
        public DbSet<box_credit> box_credit { get; set; }
        public DbSet<box_debit> box_debit { get; set; }
        public DbSet<company> company { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Currencies> Currencies { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<customer_credit> customer_credit { get; set; }
        public DbSet<customer_debit> customer_debit { get; set; }
        public DbSet<customer_ReveiveTime> customer_ReveiveTime { get; set; }
        public DbSet<error> error { get; set; }
        public DbSet<ExchangeRates> ExchangeRates { get; set; }
        public DbSet<liability> liability { get; set; }
        public DbSet<liability_credit> liability_credit { get; set; }
        public DbSet<liability_debit> liability_debit { get; set; }
        public DbSet<material> material { get; set; }
        public DbSet<material_credit> material_credit { get; set; }
        public DbSet<material_credit_list> material_credit_list { get; set; }
        public DbSet<material_credit_penfit_payment> material_credit_penfit_payment { get; set; }
        public DbSet<material_credit_return> material_credit_return { get; set; }
        public DbSet<material_debit> material_debit { get; set; }
        public DbSet<material_debit_list> material_debit_list { get; set; }
        public DbSet<material_debit_list_return> material_debit_list_return { get; set; }
        public DbSet<material_debit_penfit_payment> material_debit_penfit_payment { get; set; }
        public DbSet<material_debit_return> material_debit_return { get; set; }
        public DbSet<material_group> material_group { get; set; }
        public DbSet<material_maker> material_maker { get; set; }
        public DbSet<material_maker_list> material_maker_list { get; set; }
        public DbSet<materialMaker_credit> materialMaker_credit { get; set; }
        public DbSet<materialMaker_credit_list> materialMaker_credit_list { get; set; }
        public DbSet<paper_pay> paper_pay { get; set; }
        public DbSet<paper_pay_credit> paper_pay_credit { get; set; }
        public DbSet<paper_pay_debit> paper_pay_debit { get; set; }
        public DbSet<paper_receive> paper_receive { get; set; }
        public DbSet<paper_receive_credit> paper_receive_credit { get; set; }
        public DbSet<paper_receive_debit> paper_receive_debit { get; set; }
        public DbSet<producer> producer { get; set; }
        public DbSet<supplier> supplier { get; set; }
        public DbSet<supplier_credit> supplier_credit { get; set; }
        public DbSet<supplier_debit> supplier_debit { get; set; }
        public DbSet<supplier_PayTime> supplier_PayTime { get; set; }
        public DbSet<User_login_history> User_login_history { get; set; }
        public DbSet<user_permission> user_permission { get; set; }
        public DbSet<user_profile> user_profile { get; set; }
        public DbSet<WareHouse> WareHouse { get; set; }
        public DbSet<material_cost> material_cost { get; set; }
        public DbSet<material_credit_list_return> material_credit_list_return { get; set; }
    }
}
