//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper_pay
    {
        public paper_pay()
        {
            this.paper_pay_debit = new HashSet<paper_pay_debit>();
            this.paper_pay_credit = new HashSet<paper_pay_credit>();
        }
    
        public System.Guid الرقم { get; set; }
        public double الرصيد { get; set; }
        public string الرصيد_كتابة { get; set; }
        public Nullable<System.DateTime> تاريخ { get; set; }
        public Nullable<System.DateTime> تاريخ_الاستحقاق { get; set; }
        public string الساحب { get; set; }
        public string المسحوب_عليه { get; set; }
        public string code { get; set; }
        public Nullable<System.Guid> companyID { get; set; }
    
        public virtual ICollection<paper_pay_debit> paper_pay_debit { get; set; }
        public virtual ICollection<paper_pay_credit> paper_pay_credit { get; set; }
    }
}
