//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper_receive
    {
        public paper_receive()
        {
            this.paper_receive_debit = new HashSet<paper_receive_debit>();
            this.paper_receive_credit = new HashSet<paper_receive_credit>();
        }
    
        public System.Guid الرقم { get; set; }
        public double الرصيد { get; set; }
        public string الرصيد_كتابة { get; set; }
        public Nullable<System.DateTime> تاريخ { get; set; }
        public Nullable<System.DateTime> تاريخ_الاستحقاق { get; set; }
        public string الساحب { get; set; }
        public string المسحوب_عليه { get; set; }
        public string code { get; set; }
        public Nullable<System.Guid> companyID { get; set; }
    
        public virtual ICollection<paper_receive_debit> paper_receive_debit { get; set; }
        public virtual ICollection<paper_receive_credit> paper_receive_credit { get; set; }
    }
}
