//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class producer
    {
        public producer()
        {
            this.material = new HashSet<material>();
        }
    
        public System.Guid رقم_الصانع { get; set; }
        public string اسم_الصانع { get; set; }
        public string رمز_النوع { get; set; }
        public Nullable<System.Guid> companyID { get; set; }
    
        public virtual ICollection<material> material { get; set; }
    }
}
