//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public user_profile()
        {
            this.audit = new HashSet<audit>();
            this.User_login_history = new HashSet<User_login_history>();
            this.user_permission = new HashSet<user_permission>();
        }
    
        public System.Guid ID { get; set; }
        public string Fullname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<int> failed_attempts { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> updated_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<audit> audit { get; set; }
        public virtual ICollection<User_login_history> User_login_history { get; set; }
        public virtual ICollection<user_permission> user_permission { get; set; }
    }
}
