//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_loge_date
    {
        public int id { get; set; }
        public System.DateTime loge_date_in { get; set; }
        public Nullable<System.DateTime> loge_date_out { get; set; }
        public int user_id_ { get; set; }
    
        public virtual user_loge user_loge { get; set; }
    }
}
