//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_login_history
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<System.DateTime> session_started { get; set; }
        public Nullable<System.DateTime> session_end { get; set; }
        public string ip_address { get; set; }
        public string device_info { get; set; }
        public Nullable<int> session_duration { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual user_profile user_profile { get; set; }
    }
}
