//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public WareHouse()
        {
            this.material = new HashSet<material>();
            this.materialMaker_credit = new HashSet<materialMaker_credit>();
        }
    
        public System.Guid رقم_المستودع { get; set; }
        public string اسم_المستودع { get; set; }
        public Nullable<System.Guid> companyID { get; set; }
    
        public virtual ICollection<material> material { get; set; }
        public virtual ICollection<materialMaker_credit> materialMaker_credit { get; set; }
    }
}
