USE [master]

/****** Object:  Database [Company]    Script Date: 07/09/2013 08:34:41 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'Company')
DROP DATABASE [Company]

USE [master]

/****** Object:  Database [Company]    Script Date: 07/09/2013 08:34:41 ******/
CREATE DATABASE [Company] ON  PRIMARY 
( NAME = N'Company', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Company.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Company_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Company_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE Arabic_100_BIN2

ALTER DATABASE [Company] SET COMPATIBILITY_LEVEL = 90
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Company].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [Company] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [Company] SET ANSI_NULLS OFF 

ALTER DATABASE [Company] SET ANSI_PADDING OFF 

ALTER DATABASE [Company] SET ANSI_WARNINGS OFF 

ALTER DATABASE [Company] SET ARITHABORT OFF 

ALTER DATABASE [Company] SET AUTO_CLOSE OFF 

ALTER DATABASE [Company] SET AUTO_CREATE_STATISTICS ON 

ALTER DATABASE [Company] SET AUTO_SHRINK OFF 

ALTER DATABASE [Company] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [Company] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [Company] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [Company] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [Company] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [Company] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [Company] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [Company] SET  DISABLE_BROKER 

ALTER DATABASE [Company] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [Company] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [Company] SET TRUSTWORTHY OFF 

ALTER DATABASE [Company] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [Company] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [Company] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [Company] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [Company] SET  READ_WRITE 

ALTER DATABASE [Company] SET RECOVERY FULL 

ALTER DATABASE [Company] SET  MULTI_USER 

ALTER DATABASE [Company] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [Company] SET DB_CHAINING OFF 


